services:

    shipping_providers:
        namespace: App\Infrastructure\Domain\Model\Shipping\
        resource: '%kernel.project_dir%/src/Infrastructure/Domain/Model/Shipping/*/*ShippingGateway.php'
        arguments:
            $request: '@=service("request_stack").getCurrentRequest()'
        tags: ['app.shipping_providers']
        public: true

    shipping_providers_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: [ 'container.service_locator' ]
        arguments:
            - !tagged_iterator { tag: 'app.shipping_providers' }
